# ES200RN-120 (YR-ES200RN-A10, NX100)
# velocity in deg/s, effort in Nm
joint_1:
  velocity: 90.0
  effort: 6276.26
joint_2:
  velocity: 85.0
  effort: 6067.86
joint_3:
  velocity: 85.0
  effort: 7538.82
joint_4:
  velocity: 175.0
  effort: 1253.29
joint_5:
  velocity: 145.0
  effort: 1569.06
joint_6:
  velocity: 240.0
  effort: 617.82
